### ISSUE TITLE
Adding proxy break VS and NuGet compatibility

### ISSUE THREAD

**Issue by joel-ld** [esdc-edsc/ESDC-Development-Setup#1]
After adding the proxy on the PC, we're able to reach GitHub.

However, we can't access the Artifactory  NuGet url using Visual Studio.

I suspect these following commands : 
```bat
::System account proxy environment variables
setx HTTP_PROXY http://%USERNAME%@proxy.prv:80
setx HTTPS_PROXY http://%USERNAME%@proxy.prv:80
```

**Comment by StdGit** [comment]
I use github and VS 2015 under a proxy and  I don't have your issue
I use 
windows 7
and my link to artifactory ESDC - .net is 
https://jade-repos.intra.dev/artifactory/ca-gc-sds-libs-nuget-local/

I suggest that you open a ticket with sade.

**Comment by s-laugh** [comment]
This is actually an issue with the script. I've had a few people report the same thing including myself.
Once running the `proxy-no.bat` Artifactory works again. Maybe it's an issue with Win 10...

Further more, with the `proxy-yes` set, I can still login to Artifactory in the browser, just not run any commands against it (which is how VS accesses it). The command all return a 400 bad request error. I opened a ticket with SADE, which got escalated to Desktop Support and a few others, their only solution for me was a new computer, which as soon as I ran the script again, became an issue.

cc @ahmad-shahid

**Comment by s-laugh** [comment]
Did some more investigating and experimenting with this.   
It seems if you don't run those last to commands "::System account proxy environment variables" then you can both run npm and connect to Artifactory over command (or in VS) behind the proxy just fine. I'm wondering what value those lines actually are adding to our environment configuration...? Can we remove them with a PR?

In order to fix the issue you can run the last two lines from `proxy-no.bat`.
```bat
::System account proxy environment variables
setx HTTP_PROXY ""
setx HTTPS_PROXY ""
```
